version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django-blog
    container_name: django
    ports:
      - '8000:8000'
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    volumes:
      - .:/app
    depends_on:
      - postgres

    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"

  postgres:
    image: 'postgres'
    container_name: postgres
    env_file:
      - ./.envs/.postgres
    volumes:
      - postgres_blog_backup:/var/lib/postgresql/data


volumes:
  postgres_blog_backup:
